{
 "title": "Ammunition Overview",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "tags": [
  "ammunition",
  "go"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasourse", "label": "Datasourse", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(go_goroutines,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache len",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ammunition_cache_len_total", "legendFormat": "{{cache}}" }
   ]
  },
  {
   "title": "Total capasity memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((sum by(cache) ((ammunition_cache_cap_total) / (ammunition_cache_count)))/32000000000 )*100)",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache Capacity",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "ammunition_cache_cap_total ", "legendFormat": "{{cache}}" }
   ]
  },
  {
   "title": "Cache count",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ammunition_cache_count", "legendFormat": "{{cache}}" }
   ]
  },
  {
   "title": "Workers count",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ammunition_worker_count_total", "legendFormat": "{{cache}}" }
   ]
  },
  {
   "title": "Cache overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(ammunition_http_requests_duration_ms_sum[30s]))/sum(rate(ammunition_http_requests_duration_ms_count[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "rate(ammunition_http_requests_duration_ms[30s])",
       "legendFormat": "{{path}} - {{method}}  - quantile {{quantile}}"
      }
     ]
    },
    {
     "title": "Worker time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (cache) (rate(ammunition_worker_duration_ms[30s]))",
       "legendFormat": "avg {{cache}}"
      },
      {
       "expr": "rate(ammunition_worker_duration_ms[30s])",
       "legendFormat": "{{cache}}  - quantile {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go metrics ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\"}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\"}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "process memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{job=\"$job\"}[30s])",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "rate(process_virtual_memory_bytes{job=\"$job\"}[30s])",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[30s])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes{job=\"$job\"}[30s])",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[30s])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$job\"}[30s])",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "rate(go_memstats_heap_inuse_bytes{job=\"$job\"}[30s])",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_open_fds{job=\"$job\"}[30s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\"}",
       "legendFormat": "{{pod}}: {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Basic CPU info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"system\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "system"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"user\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "user"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"iowait\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "iowait"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"steal\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "steal"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"softirq\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "softirq"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"irq\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "irq"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"nice\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "nice"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"nice\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "steal"
      },
      {
       "expr": "instance:node_cpu_seconds_total:irate5m{mode=\"idle\", instance=\"172.27.194.51:9100\"}",
       "legendFormat": "idle"
      }
     ]
    },
    {
     "title": "Context Switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "instance:node_context_switches_total:rate1m{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "Switch"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.27.194.51:9100\"} - node_memory_MemAvailable_bytes{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.27.194.51:9100\"} + node_memory_Buffers_bytes{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "Cache + Buffer"
      }
     ]
    },
    {
     "title": "Memory active/inactive (byte/sec)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "instance:node_memory_Active_bytes:rate1m{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "active"
      },
      {
       "expr": "instance:node_network_receive_bytes_total:irate1m{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "Inactive"
      }
     ]
    },
    {
     "title": "Netstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "tw"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "used"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "allocate"
      },
      {
       "expr": "instance:node_netstat_Tcp_PassiveOpens:irate30s{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "PassiveOpen"
      },
      {
       "expr": "instance:node_netstat_Tcp_ActiveOpens:irate30s{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "ActiveOpens"
      },
      {
       "expr": "instance:node_netstat_Tcp_InSegs:irate30s{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "InSegs"
      },
      {
       "expr": "instance:node_netstat_Tcp_OutSegs:irate30s{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "OutSegs"
      },
      {
       "expr": "instance:node_netstat_Tcp_RetransSegs:irate30s{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "RetransSeg"
      },
      {
       "expr": "instance:node_netstat_TcpExt_ListenDrops:irate30s{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "ListenDrop"
      }
     ]
    },
    {
     "title": "traff",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": " instance:node_network_receive_bytes_total:irate1m{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "recive {{device}}"
      },
      {
       "expr": "instance:node_network_transmit_bytes_total:irate1m{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "transmit  {{device}}"
      }
     ]
    },
    {
     "title": "filefd_allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "filefd_allocated"
      }
     ]
    },
    {
     "title": "filefd_allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=\"172.27.194.51:9100\"}",
       "legendFormat": "filefd_allocated"
      }
     ]
    }
   ]
  }
 ]
}