{
 "title": "Kafka Exporter Overview",
 "tags": [ "Kafka" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(kafka_topic_partitions, group)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(kafka_topic_partitions{group=~\"$group\"}, service)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(kafka_topic_partitions{service=\"$service\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka:kafka_consumergroup_lag:sum{instance=~\"$host.+\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host.+\"} - node_boot_time_seconds{instance=~\"$host.+\"}"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{instance=~\"$host.+\"}"
    }
   ]
  },
  {
   "title": "Replicas count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{instance=~\"$host.+\"})by(host)",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-instance:node_cpu_seconds_total:irate5m{mode='idle',instance=~\"$host.+\"}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node_memory_load_bytes:total{instance=~\"$host.+\"}"
    }
   ]
  },
  {
   "title": "Disk free Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node_filesystem_free_total_bytes:sum{instance=~\"$host.+\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "NetStat",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$host.+\"}",
     "legendFormat": "TW"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$host.+\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$host.+\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$host.+\"}",
     "legendFormat": "Allocate"
    },
    {
     "expr": "instance:node_netstat_Tcp_PassiveOpens:irate30s{instance=~\"$host.+\"}",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": " instance:node_netstat_Tcp_ActiveOpens:irate30s{instance=~\"$host.+\"}",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "instance:node_netstat_Tcp_InSegs:irate30s{instance=~\"$host.+\"}",
     "legendFormat": "InSegs"
    },
    {
     "expr": "instance:node_netstat_Tcp_OutSegs:irate30s{instance=~\"$host.+\"}",
     "legendFormat": "OutSegs"
    },
    {
     "expr": " instance:node_netstat_Tcp_RetransSegs:irate30s{instance=~\"$host.+\"}",
     "legendFormat": "RetransSegs"
    },
    {
     "expr": "instance:node_netstat_TcpExt_ListenDrops:irate30s{instance=~\"$host.+\"}",
     "legendFormat": "ListenDrops"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_core:count{instance=~\"$host.+\"}"
    }
   ]
  },
  {
   "title": "Leader count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_leader{instance=~\"$host.+\"})by(host)",
     "legendFormat": "Leader"
    }
   ]
  },
  {
   "title": "Partitions count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{instance=~\"$host.+\"})"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "instance:node_swap_usage:total{instance=~\"$host.+\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host.+\"}"
    }
   ]
  },
  {
   "title": "Topic info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lag by  Consumer Group",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka:kafka_consumergroup_lag:sum{instance=~\"$host.+\",topic=~\"$topic\"}",
       "legendFormat": "{{consumergroup}} (topic: {{topic}})"
      }
     ]
    },
    {
     "title": "Partitions per Topic",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka:kafka_topic_partitions:sum{instance=~\"$host.+\",topic=~\"$topic\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message in per second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka:kafka_topic_partition_current_offset:sumbyrate1m{instance=~\"$host.+\",topic=~\"$topic\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message consume per minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka:kafka_consumergroup_current_offset:sumbydelta5m{instance=~\"$host.+\",topic=~\"$topic\"}",
       "legendFormat": "{{consumergroup}} (topic: {{topic}})"
      }
     ]
    }
   ]
  }
 ]
}