{
 "title": "OpenShift Sevice Overview",
 "tags": [ "openshift" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "project_mg",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "pods_mg",
    "label": "Pods",
    "query": {
     "query": "label_values(pod:container_cpu_usage:sum{namespace=\"$project_mg\"}, pod)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "POD | CPU Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "POD $pods_mg",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "repeat": "pods_mg",
     "targets": [
      {
       "expr": "container_spec_cpu_quota{namespace=\"$project_mg\", container!=\"\", pod=\"$pods_mg\"} / 100000",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | Memory Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "POD $pods_mg",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "repeat": "pods_mg",
     "targets": [
      {
       "expr": "container_spec_memory_limit_bytes{namespace=\"$project_mg\", pod=\"$pods_mg\", container!=\"\", container!=\"POD\"} / 1024 /1024",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD  | CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики CPU поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "container:container_cpu_usage_by_quota:avg{pod=~'$pods_mg', container!=\"\"}",
       "legendFormat": "container: {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | Memory  usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage для поды $pods_mg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "repeat": "pods_mg",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "container:container_memory_usage_bytes:total {namespace=\"$project_mg\", pod=~\"$pods_mg\", container!=\"POD\", container!=\"container\", container!=\"\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "container: {{container}}"
      },
      {
       "expr": "container:container_memory_total_bytes:sum {namespace=\"$project_mg\", pod=~\"$pods_mg\", container!=\"POD\", container!=\"container\", container!=\"\",prometheus_replica=\"prometheus-k8s-1\"}",
       "legendFormat": "TOTAL"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | Memory usage MB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage для поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container:container_memory_pod_total_bytes:sum{namespace=\"$project_mg\", pod=~\"$pods_mg\", container!=\"POD\", container!=\"container\", container!=\"\"})by(container)",
       "legendFormat": "container: {{container}}"
      },
      {
       "expr": "sum(container:container_memory_pod_total_bytes:sum{namespace=\"$project_mg\", pod=~\"$pods_mg\", container!=\"POD\", container!=\"container\", container!=\"\"})",
       "legendFormat": "TOTAL"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | SWAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики SWAP поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container:node_namespace_pod_container_memory_swap:rate5m{namespace=\"$project_mg\",pod=\"$pods_mg\", container!=\"\", container!=\"POD\"}",
       "legendFormat": "container: {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Утилизация сети для поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "container:container_network_receive_bytes_total:rate5m{namespace=\"$project_mg\", pod=\"$pods_mg\"}",
       "legendFormat": "receive"
      },
      {
       "expr": "container:container_network_transmit_bytes_total:rate5m{namespace=\"$project_mg\", pod=\"$pods_mg\"}",
       "legendFormat": "transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | HEAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики JVM Memory  HEAP поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\", pod=~'$pods_mg'}",
       "legendFormat": "Usage: {{id}}"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\",pod=~'$pods_mg'}",
       "legendFormat": "Max: {{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD |  Non-HEAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики JVM Memory  Non-HEAP поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area!=\"heap\", pod=~'$pods_mg'}",
       "legendFormat": "Usage: {{id}}"
      },
      {
       "expr": "jvm_memory_max_bytes{area!=\"heap\",pod=~'$pods_mg'}",
       "legendFormat": "Max: {{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики Thread поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{pod=~'$pods_mg'}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{pod=~'$pods_mg'}",
       "legendFormat": "Peak"
      },
      {
       "expr": "jvm_threads_states_threads{pod=~'$pods_mg'}",
       "legendFormat": "States {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | Buffer info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики Buffers memory поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{pod=~'$pods_mg'}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{pod=~'$pods_mg'}",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "Метрики Buffers count поды $pods_mg",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "repeat": "pods_mg",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{pod=~'$pods_mg'}",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | GC info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики GC data size поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_gc_max_data_size_bytes{pod=~'$pods_mg'}",
       "legendFormat": "Max data size"
      },
      {
       "expr": "jvm_gc_live_data_size_bytes{pod=~'$pods_mg'}",
       "legendFormat": "Live data size"
      }
     ]
    },
    {
     "title": "Метрики GC  pause поды $pods_mg",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm:gc_pause_seconds_count:rate1m{pod=~'$pods_mg'}",
       "legendFormat": "Count {{cause}}"
      },
      {
       "expr": "\njvm_gc_pause_seconds_max{pod=~'$pods_mg'}",
       "legendFormat": "Max  {{cause}}"
      },
      {
       "expr": " jvm:gc_pause_seconds_sum:rate1m{pod=~'$pods_mg'}",
       "legendFormat": "Sum  {{cause}}"
      }
     ]
    },
    {
     "title": "Метрики GC  memory поды $pods_mg",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "repeat": "pods_mg",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm:gc_memory_promoted_bytes_total:rate1m{pod=~'$pods_mg'}",
       "legendFormat": "Promoted"
      },
      {
       "expr": " jvm:gc_memory_allocated_bytes_total:rate1m{pod=~'$pods_mg'}",
       "legendFormat": "Allocated"
      }
     ]
    }
   ]
  },
  {
   "title": "POD | Java Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики Java Classes поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": " jvm:classes_loaded_classes:rate1m{pod=~'$pods_mg'}",
       "legendFormat": "Loaded"
      },
      {
       "expr": "jvm:classes_unloaded_classes_totalrate1m{pod=~'$pods_mg'}",
       "legendFormat": "Unloaded"
      }
     ]
    }
   ]
  }
 ]
}