{
 "title": "SSD Session overview",
 "tags": [
  "openshift",
  "SSD session"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_mg",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "pods_mg",
    "label": "Pods",
    "query": {
     "query": "label_values(pod:container_cpu_usage:sum{namespace=\"$project_mg\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UFS Session proxy info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Keycloack success counter total by pod (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(keycloack_success_counter_total[30s])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Keycloack fail total by pod (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(keycloack_fail_counter_total[30s])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Provider  succes total by pod (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ufs_provider_success_counter_total[30s])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Provider  fail total by pod (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ufs_provider_fail_counter_total[30s])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Check seconds count (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(check_session_counter_seconds_count[30s]))by(instance,pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": " Check seconds sum (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(check_session_counter_seconds_sum[30s]))by(instance,pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Check seconds sum (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(check_session_counter_seconds_max[30s]))by(instance,pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Create seconds count (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(create_session_counter_seconds_count[30s]))by(instance,pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Create seconds count (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(create_session_counter_seconds_max[30s]))by(instance,pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Create seconds count (Rate 30s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(create_session_counter_seconds_sum[30s]))by(instance,pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UFS SDS Session info | once graph by metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Servant Session count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "esf_session_count", "legendFormat": "Count sum" },
      {
       "expr": "ufs_session:sds_servant_register_session_count:rate30s",
       "legendFormat": "Register Count rate"
      },
      {
       "expr": "UFS_SDS_SERVANT_REGISTER_SESSIONS_COUNT_max",
       "legendFormat": "Register Max"
      }
     ]
    },
    {
     "title": "Master Active Session count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "UFS_SDS_ACTIVE_SESSION_COUNT_max{pod!~\"ufs-session-servant.+\"}",
       "legendFormat": "Active Session {{pod}}"
      }
     ]
    },
    {
     "title": "Net latency  rq slave -> master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ufs_session:plt_rest_duration_sum:rate30s{service=\"ufs-provider\", clientModuleName=\"sds.master\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Duration method put",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ufs_session:sds_master_duration_max:sum{ufsModule_consumerServiceUrl=\"/ufs-session-master/rest/v3/inner/saveSessionSections\"}",
       "legendFormat": "Duration by {{pod}}"
      }
     ]
    },
    {
     "title": "Duration method get",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ufs_session:sds_master_duration_max:sum{ufsModule_consumerServiceUrl=\"/ufs-session-master/rest/v3/inner/getSessionSections\"}",
       "legendFormat": "Duration by {{pod}}"
      }
     ]
    },
    {
     "title": "Max duration method (all pod)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ufs_session:sds_master_duration_max:max",
       "legendFormat": "Max Duration by method  {{ufsModule_consumerServiceUrl}}"
      }
     ]
    },
    {
     "title": "AVG duration method (all pod)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ufs_session:plt_rest_duration:total{clientModuleName=\"sds.master\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Slave  avg duration method (all pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ufs_session:ssds_slave_duration_sum:avg_rate30s",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Master RPS duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "ufs_session:sds_master_duration_count:sum_rate30s",
       "legendFormat": "RPS by  {{pod}}"
      }
     ]
    },
    {
     "title": "Slave RPS duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "ufs_session:sds_slave_duration_count:sum_rate30s",
       "legendFormat": "RPS by  {{pod}}"
      }
     ]
    },
    {
     "title": "Slave cache miss",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:sds_sticky_session_mistake_detected_count:rate30s",
       "legendFormat": "  {{pod}}"
      }
     ]
    },
    {
     "title": "Slave get session duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "UFS_SDS_SLAVE_DURATION_max{method=\"/ufs-session-slave/rest/v3/core/getSession\"}",
       "legendFormat": "  {{pod}}"
      }
     ]
    },
    {
     "title": "master - New session count -  rate 60 second",
     "type": "timeseries",
     "description": "retantion 24h\nTODO\npush in the cortex",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_new_session_succes:rate1m{pod=~\"ufs-session.+\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "master - Active session count -  rate 60 second",
     "type": "timeseries",
     "description": "retantion 24h\nTODO\npush in the cortex",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_active_session_count:rate1m{pod=~\"ufs-session.+\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "master - Section write count -  rate 60 second",
     "type": "timeseries",
     "description": "retantion 24h\nTODO\npush in the cortex",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_section_write_count:rate1m{pod=~\"ufs-session.+\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "master - Invalidate session write count -  rate 60 second",
     "type": "timeseries",
     "description": "retantion 24h\nTODO\npush in the cortex",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_invalidate_session_write_count:rate1m{pod=~\"ufs-session.+\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "master - Invalidate session read count -  rate 60 second",
     "type": "timeseries",
     "description": "retantion 24h\nTODO\npush in the cortex",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_invalidate_session_read_count:rate1m{pod=~\"ufs-session.+\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "master - timeout session lifetime -  rate 60 second",
     "type": "graph",
     "description": "retantion 24h\nTODO\npush in the cortex",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "yaxes": [
      { "format": "m" }
     ],
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_invalidate_by_timeout_session_read_count:rate1m",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Slave duration count by pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_slave_duration_count:rate1m",
       "legendFormat": "{{pod}} -  {{method}}"
      }
     ]
    },
    {
     "title": "Slave duration max by pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": " ufs_session:ufs_sds_slave_duration_max:rate1m",
       "legendFormat": "{{pod}} - {{method}}"
      }
     ]
    },
    {
     "title": "Slave duration sum by  pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_slave_duration_sum:rate1m",
       "legendFormat": "{{pod}} - {{method}}"
      }
     ]
    },
    {
     "title": "Delete empty session from slave  cache count  by  pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_delete_empty_session_from_slave_cashe_count:rate1m",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Delete empty session from slave  cache max  by  pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_delete_empty_session_from_slave_cashe_max:rate1m",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Delete empty session from slave  cache sum  by  pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 193 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ufs_session:ufs_sds_delete_empty_session_from_slave_cashe_sum:rate1m",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UFS SDS Session info | single graph by pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "USF SDS Slave duration  sum поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ufs_session:sds_slave_duration_sum:irate30s{pod=~'$pods_mg'}",
       "legendFormat": "Loaded"
      }
     ]
    },
    {
     "title": "USF SDS Slave duration  max поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ufs_session:sds_slave_duration_max:irate30s{pod=~'$pods_mg'}",
       "legendFormat": "Loaded"
      }
     ]
    },
    {
     "title": "USF SDS Slave duration  count поды $pods_mg",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 39 },
     "repeat": "pods_mg",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ufs_session:sds_slave_duration_count:irate30s{pod=~'$pods_mg'}",
       "legendFormat": "Loaded"
      }
     ]
    }
   ]
  }
 ]
}