global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
   - "linux_host_rules.yml"
   - "postgres_rules.yml"
   - "kafka_rules.yml"
   - "opensift_container_rules.yml"
   - "opensift_ufssession_rules.yml"
   - "haproxy_rules.yml"

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['pkles-gt0002950.solution.gt:9323']
  - job_name: 'docker_swarm'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks

#example remote prometheus
remote_write:
  - url: "http://${PROMETHEUS_MAIN}:9090/api/v1/write"