global:
  scrape_interval:     10s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['${SWARM_MASTER_DEPLOY_NODE}:9323']
  - job_name: 'docker_swarm'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks

#example remote prometheus
remote_write:
  - url: "http://${PROMETHEUS_MAIN}:9090/api/v1/write"