apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: false
  - name: Prometheus_main_storage
    type: prometheus
    url: http:/${PROMETHEUS_MAIN_NODE}:9090
    access: proxy
    basicAuth: false
  - name: Prometheus_scraper_storage
    type: prometheus
    url: http:/${PROMETHEUS_SCRAPER_NODE}:9090
    access: proxy
    basicAuth: false
     