groups:
  - name: jmeter_requests
    rules:
    - record: jmeter:requests:sum_rate30s
      expr: sum by (projectName,testName,runId,isTransaction,parent,requestStatus,responseCode) (rate(jmeter_requests[30s]))   
    - record: jmeter:active_threads:sum
      expr: sum by (projectName,testName,nodeName,runId) (jmeter_active_threads)
  - name: jmeter_response_time
    rules:
    - record: jmeter:response_time:avg
      expr: avg(jmeter_response_time >= 0)by(projectName,testName,runId,isTransaction,parent,requestName,quantile)
    - record: jmeter:response_time_total_sum:sum_rate30s
      expr: sum(rate(jmeter_response_time_sum[30s])) by(projectName,testName,runId,isTransaction,parent,requestName)
    - record: jmeter:response_time_count_total:sum_rate30s
      expr: sum(rate(jmeter_response_time_count[30s])) by (projectName,testName,runId,isTransaction,parent,requestName)
    - record: jmeter:response_time_total:sum_rate30s
      expr: |2
          jmeter:response_time_total_sum:sum_rate30s
        /
          jmeter:response_time_count_total:sum_rate30s
